POST http://{{host}}:{{port}}/group/add?name=gbb&receiverId=2&receiverId=3
Accept: */*
Cache-Control: no-cache

###

POST http://{{host}}:{{port}}/group/add?name=gcc&receiverId=4&receiverId=5
Accept: */*
Cache-Control: no-cache

###

GET http://{{host}}:{{port}}/group/list
Accept: */*
Cache-Control: no-cache

###

GET http://{{host}}:{{port}}/group/get?id=11
Accept: */*
Cache-Control: no-cache

###

GET http://{{host}}:{{port}}/group/delete?id=3
Accept: */*
Cache-Control: no-cache

###