POST http://{{host}}:{{port}}/message/add?subject=测试邮件&content=HelloWorld！
Accept: */*
Cache-Control: no-cache

###

POST http://{{host}}:{{port}}/message/add?subject=mbb&content=bbccddee
Accept: */*
Cache-Control: no-cache

###

GET http://{{host}}:{{port}}/message/list
Accept: */*
Cache-Control: no-cache

###

GET http://{{host}}:{{port}}/message/delete?id=1
Accept: */*
Cache-Control: no-cache

###

POST http://{{host}}:{{port}}/message/set?id=1&subject=测试邮件666&content=HelloWorld！777
Accept: */*
Cache-Control: no-cache

###