POST http://{{host}}:{{port}}/receiver/add?name=赵rf&email=591075865@qq.com
Accept: */*
Cache-Control: no-cache

###

POST http://{{host}}:{{port}}/receiver/add?name=bb&email=bb@email.com
Accept: */*
Cache-Control: no-cache

###

POST http://{{host}}:{{port}}/receiver/add?name=cc&email=cc@email.com
Accept: */*
Cache-Control: no-cache

###

GET http://{{host}}:{{port}}/receiver/list
Accept: */*
Cache-Control: no-cache

###

GET http://{{host}}:{{port}}/receiver/delete?id=2
Accept: */*
Cache-Control: no-cache

###

POST http://{{host}}:{{port}}/receiver/set?id=6&email=i@leop.pro55&name=abc99
Accept: */*
Cache-Control: no-cache

###