GET http://{{host}}:{{port}}/sender/heartbeat
Accept: */*
Cache-Control: no-cache

###

GET http://{{host}}:8080/sender/list
Accept: */*
Cache-Control: no-cache

###

GET http://{{host}}:{{port}}/sender/get?id=0
Accept: */*
Cache-Control: no-cache

###