POST http://{{host}}:{{port}}/task/add?name=测试任务&messageId=1&cron=30 * * * * ? *&senderId=0&groupId=1&groupId=2&groupId=3
Accept: */*
Cache-Control: no-cache

###

GET http://{{host}}:{{port}}/task/list
Accept: */*
Cache-Control: no-cache

###

GET http://{{host}}:{{port}}/task/delete?id=2
Accept: */*
Cache-Control: no-cache

###

